### ISSUE TITLE
Produce physical resources

### ISSUE THREAD

**Issue by DPeterK** [scitools-classroom/courses#104]
One way to boost learning is to improve the physical environment within which these courses are taught. We could do this by producing posters that relate to the teaching material that are added to the learning environment.

The resources should be primarily graphical and ideally colourful too. Some possible examples:

* The NumPy broadcasting example image
* The different types of matplotlib plots shown in the course
* The pictographic representation of a cube
* Cube data plotted on a cartopy map

**Comment by pelson** [comment]
Neat idea. 👍 
A cheatsheet is another option.


In the interest of not having issues sitting around, do you want to action something from this, or are you just wanting to raise awareness? If the latter let's close the issue. (FWIW I think having visual cues is a great idea)

**Comment by dkillick** [comment]
@pelson I raised this so that (a) I wouldn't forget the idea, and (b) to get feedback from others. Given that I now have some positive feedback I might look to implementing this when we next spend some time thinking about the courses - so if you don't mind can we keep this open so I keep on not forgetting the idea?
